### PR TITLE
Materialize styles.

### PR DESCRIPTION
**Pull request by Sivli-Embir**
Adding this now so its visible. @splendido I will ping you when its ready.

### CODE REVIEW

**Comment by splendido** [comment]
would you like me to merge this now?

**Comment by Sivli-Embir** [comment]
If you wish. It works great for password only as far as I can tell. I still need to add support social buttons and test optionals like terms.

**Comment by splendido** [comment]
Ok, I'll wait a bit more.
it would be great if you could also push a boilerplate for this :-)

**Comment by Sivli-Embir** [comment]
Boilerplate? How so?

**Comment by Sivli-Embir** [comment]
It is not perfect but it is usable. We can push it as is but we need to specify it was last updated for MaterializeCSS `alpha release v0.95.1`.

**Comment by sireskay** [comment]
Thanks @Kestanous I haven't look at the code yet, but I wanted to thank you for your progress thus far.

**Comment by splendido** [comment]
@Kestanous there's a boilerplate under meteor-useraccounts,  lets have a look at it.  (I'm sorry I'm not at the PC right now...)

Thanks for taking the lead on this!

**Comment by Sivli-Embir** [comment]
Thanks for clarifying and here you go https://github.com/meteor-useraccounts/boilerplates/pull/6!

**Pull request merged**
